### ISSUE TITLE
Consistency-check IODC/IODE across all three subframes of nav msg

### ISSUE THREAD

**Issue by henryhallam** [swift-nav/libswiftnav#159]
/cc @fnoble @mookerji 
Per the interface spec, the first three subframes (which comprise the clock correction curve and the ephemeris) each include an Issue Of Data field - IODC in subframe 1 and IODE in each of subframes 2 and 3.  This is provided so the receiver can ensure that it uses data from a complete set, and doesn't mix and match across ephemeris updates.  Presently, we load IODE into the ephemeris struct and never look at it, and we don't even record IODC at all.

This isn't an urgent problem because of the rather conservative logic in nav_msg.c:process_subframe(), which will only call decode_ephemeris() when it has received 3 valid (i.e. passing parity) subframes in a row, in the strict order 1,2,3.  I'm pretty sure the changeover of the actual transmitted message from one set to the next occurs on a 30 second boundary, i.e. between transmission of subframe 5 and 1, so I don't think it's possible to do any of that kind of mixing + matching with the current code.  But by using the IODC/IODE as intended, we'd be able to improve time to first single-ended fix by up to 12 seconds in some cases.  And it's a useful belt-and-braces check.

**Comment by fnoble** [comment]
I believe the ICD says its ok if IODC != IODE?

**Comment by henryhallam** [comment]
"The issue of ephemeris data (IODE) term shall provide the user with a convenient means for
detecting any change in the ephemeris representation parameters. The IODE is provided in both
subframes 2 and 3 for the purpose of comparison with the 8 LSBs of the IODC term in subframe
1. Whenever these three terms do not match, a data set cutover has occurred and new data must
be collected. The timing of the IODE and constraints on the IODC and IODE are defined in
paragraph 20.3.4.4."

**Comment by ljbade** [comment]
Done in https://github.com/swift-nav/libswiftnav/pull/255
