### ISSUE TITLE
sats management should probably fail loudly with an Null pointer passed to it.

### ISSUE THREAD

**Issue by denniszollo** [swift-nav/libswiftnav#171]
Perhaps replace this with an assert/ screaming death
https://github.com/swift-nav/libswiftnav/blob/a66b61863c07e82b1ee80404333feafd76d8db94/src/sats_management.c#L174

We have seen a handful of crashes in HITL in the firmware with the last message of "INFO: Initializing DGNSS filters", so this initilization code path is a little suspect to me.

**Comment by imh** [comment]
I looked at this and the rest of the null checks in libswiftnav. They are all like this, where it's not a silent fail, but actually extra behaviour. I'm going to leave it alone.
