### ISSUE TITLE
issue with python install

### ISSUE THREAD

**Issue by geoffreymbrown** [swift-nav/libswiftnav#236]
When executing  "python setup.py install" in the python directory, the following fatal error installs (there are several related ones) indicating access to a data structure member that does not exist.

cythoning swiftnav/track.pyx to swiftnav/track.c
building 'swiftnav.track' extension
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include -I. -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c swiftnav/track.c -o build/temp.macosx-10.10-x86_64-2.7/swiftnav/track.o -O0 -g
swiftnav/track.c:1468:22: error: no member named 'prn' in
      'channel_measurement_t'
  __pyx_v_self->meas.prn = __pyx_t_1;
  ~~~~~~~~~~~~~~~~~~ ^
swiftnav/track.c:1597:59: error: no member named 'prn' in
      'channel_measurement_t'
  __pyx_t_1 = __Pyx_PyInt_From_uint8_t(__pyx_v_self->meas.prn); if (unli...

**Comment by mookerji** [comment]
hey @geoffreymbrown, thanks for filing the bug! We're currently transitioning over the Python bindings from another repository and updating them, since their pretty out of date. The current PR (https://github.com/swift-nav/libswiftnav/pull/228) will likely get merged in the next few days?

**Comment by geoffreymbrown** [comment]
Thanks !   If I pull an earlier version to build, which one is likely to
work ?
Geoffrey

**Comment by mookerji** [comment]
@geoffreymbrown : try the new version and let me know how it goes? Thanks!
