### ISSUE TITLE
Possible errors in vector_distance()

### ISSUE THREAD

**Issue by valeri-atamaniouk** [swift-nav/libswiftnav#275]
It seems that vector_distance function has couple of issues:
- It ignores the dimension parameter, and assumes that the input vectors have length of 3
- It performs square root operation two times: vector_norm() already takes a root.

**Comment by ljbade** [comment]
@swift-nav/firmware Is this an easy fix?

**Comment by ljbade** [comment]
@valeri-atamaniouk I checked and you are right. I am making a PR.
