### ISSUE TITLE
ecef2ned error

### ISSUE THREAD

**Issue by nickrehm** [swift-nav/libswiftnav#33]
wgsecef2ned in coord_system.c passes the reference position as ECEF coordinate rather than LLA to ecef2ned_matrix

**Comment by jbangelo** [comment]
Hello @nickrehm , thank you for the report. If you examine the implementation of the `ecef2ned_matrix()` function you'll see that it internally will convert the reference ECEF coordinates into LLH coordinates before creating the rotation matrix.

https://github.com/swift-nav/libswiftnav/blob/374a792991926c8f7b10fc3d9e3da2e31f8d5cd9/src/coord_system.c#L251-L255

Does this answer your question?

**Comment by silverjam** [comment]
Hello @nickrehm -- I hope @jbangelo resolved your question so I will close this issue for now, if you have further questions feel free to comment or re-open.  Formal support requests from our team can be submitted here: https://support.swiftnav.com/support/tickets/new.  Thanks!
