### ISSUE TITLE
Lack of calc_sat_state() return code checking causes errors

### ISSUE THREAD

**Issue by jacobmcnamee** [swift-nav/libswiftnav#344]
`GPS L1CA 30 Using invalid or too old ephemeris in calc_sat_state`
`ERROR: /Swift/piksi_firmware/libswiftnav/clapack-3.2.1-CMAKE/SRC/dormrz.c:dormrz_():45 : assertion '0 && "dormrz_ was called. This function allocates too much" " memory and has been disabled."' failed`

Also applies to usage in piksi_firmware

**Comment by rge-exafore** [comment]
[i344-analysis-20160511-rge.txt](https://github.com/swift-nav/libswiftnav/files/258978/i344-analysis-20160511-rge.txt)
LSN(private) PR: https://github.com/swift-nav/libswiftnav-private/pull/4
PF PR: https://github.com/swift-nav/piksi_firmware/pull/669

**Comment by rge-exafore** [comment]
One more observation:
On three devices that happened in one run. TOW was 288206400, 288206400, 288206299. So, essentially with 100 ms accuracy at the same time. Can't be by accident, IMO.
Logs:
serial-link-20160511-005836-62315.log.json
serial-link-20160511-005836-28807.log.json
serial-link-20160511-005836-28803.log.json
(logs uploaded to https://drive.google.com/open?id=0B3xFTht-_2hJS2NIRWJROUdIT3M)

**Comment by rge-exafore** [comment]
HITL test: Firmware: piksi_firmware_v0.21-201-ge63bc43.hex

**Comment by jacobmcnamee** [comment]
The `receiver_time` field in the `channel_measurement_t` struct is populated with a time based on a u32 sample count. The `nav_time` value passed into `calc_navigation_measurement()` is also computed based on a u32 sample count. 

Problems can occur when one of those u32 values has overflowed but the other has not: `TOTs[i] += (nav_time - meas[i]->receiver_time) * meas[i]->code_phase_rate / 1.023e6`. We then use that value as the time passed to `calc_sat_state()`.

In Roman's log, `calc_sat_state()` was called from `calc_navigation_measurement()` with time = `287944.028772` when the TOW (based on the most recent solution output) should have been `288206.5`. The difference is very close to 262s, which is the period of the u32 sample counter overflow.

This indicates that measurement receiver time had NOT overflowed, but the `nav_time` value passed to `calc_navigation_measurement()` had. Thus `TOTs[i] -= ~262s`. When that happens right after a new ephemeris has been received, `calc_sat_state()` gets called with a time in the past, before the new ephemeris existed. In fact, in Roman's log, the new ephemeris was valid starting at TOW = `288000`.

**Comment by jacobmcnamee** [comment]
I have some changes made for other purposes which happen to fix this. See https://github.com/swift-nav/libswiftnav/pull/347 and https://github.com/swift-nav/piksi_firmware/pull/674

**Comment by rge-exafore** [comment]
PRs:
https://github.com/swift-nav/libswiftnav/pull/345
https://github.com/swift-nav/libswiftnav-private/pull/4
https://github.com/swift-nav/piksi_firmware/pull/669
HITL test: [link](http://sbp-log-analysis.swiftnav.com/#/d/0/q/x/firmware/y/metric/f/firmware/sv/piksi_firmware_v0.21-205-g761aba4.hex/st/1?_k=4omv28)

**Comment by ljbade** [comment]
Im confused, is this PR still needing review?

**Comment by ljbade** [comment]
Oh wait the PRs have been merged.

@rge-exafore Can this issue be closed then?

**Comment by rge-exafore** [comment]
Yes, it can be closed. Sorry. Doing that now.
