### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [swift-nav/libswiftnav#46]
Would you like to [replace any double quotes](https://github.com/swift-nav/libswiftnav/blob/ecb4aa1f13e8b7fa597a26ab811806300a2b134f/include/libswiftnav/track.h#L16 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by ljbade** [comment]
Done in https://github.com/swift-nav/libswiftnav/pull/262

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/swift-nav/libswiftnav/commit/e17ae75a3198d45d7b03fb4c840141356b99ca89 "Rename gpstime.c to time.c.").
